# Generated by Django 5.2.16 on 2026-09-03 01:55

import django.db.models.deletion
import notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=notifications.models.make_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('target_role', models.CharField(blank=True, choices=[('student', 'Student'), ('nurse_staff', 'Nurse Staff'), ('admin', 'Admin'), ('all', 'All')], max_length=20, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('request_status', 'Request Status'), ('due_reminder', 'Due Reminder'), ('overdue', 'Overdue'), ('maintenance', 'Maintenance'), ('general', 'General')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
