# Generated by Django 5.2.16 on 2026-09-03 01:55

import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabRoom',
            fields=[
                ('id', models.CharField(default=rooms.models.make_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('floor', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('supervisor', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('MAINTENANCE', 'Maintenance')], max_length=20)),
                ('active_class', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
