# Generated by Django 5.2.16 on 2026-09-03 01:55

import equipment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.CharField(default=equipment.models.make_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Nursing Skills', 'Nursing Skills'), ('Maternity & Child Health', 'Maternity & Child Health'), ('Emergency & Critical Care', 'Emergency & Critical Care'), ('Anatomy & Physiology', 'Anatomy & Physiology'), ('Diagnostic & Vital Signs', 'Diagnostic & Vital Signs'), ('Surgical & Sterile Instruments', 'Surgical & Sterile Instruments'), ('Pharmacology & Labware', 'Pharmacology & Labware')], max_length=80)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('total_quantity', models.PositiveIntegerField()),
                ('available_quantity', models.PositiveIntegerField()),
                ('borrowed_quantity', models.PositiveIntegerField(default=0)),
                ('maintenance_quantity', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('MAINTENANCE_REQUIRED', 'Maintenance Required'), ('DAMAGED', 'Damaged')], max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, default='')),
                ('specifications', models.JSONField(default=list)),
                ('usage_guidelines', models.JSONField(default=list)),
                ('is_consumable', models.BooleanField(default=False)),
                ('requires_special_approval', models.BooleanField(default=False)),
                ('qr_code', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
