# Generated by Django 5.2.16 on 2026-09-03 01:55

import django.db.models.deletion
import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.CharField(default=maintenance.models.make_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('issue_description', models.TextField()),
                ('reported_by', models.CharField(max_length=255)),
                ('reported_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SCRAPPED', 'Scrapped')], default='SCHEDULED', max_length=20)),
                ('technician', models.CharField(blank=True, default='', max_length=255)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='equipment.equipment')),
            ],
        ),
    ]
