import { Equipment, BorrowingRequest, User, LabRoom, MaintenanceRecord, Notification } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-student-1',
    name: 'Siti Nurhaliza Putri',
    nim_nip: '2102041019',
    email: 'siti.nurhaliza@mhs.ichsansatya.ac.id',
    role: 'student',
    department: 'S1 Keperawatan',
    studyProgram: 'Keperawatan & Profesi Ners',
    semester: 6,
    phone: '0812-9842-1102',
    avatar: 'https://images.unsplash.com/photo-1594824813589-9a25b7460e4d?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    joinedDate: '2021-09-01',
  },
  {
    id: 'usr-student-2',
    name: 'Dimas Arya Pratama',
    nim_nip: '2102041044',
    email: 'dimas.arya@mhs.ichsansatya.ac.id',
    role: 'student',
    department: 'Profesi Ners',
    studyProgram: 'Profesi Ners Tingkat 1',
    semester: 2,
    phone: '0857-3312-9901',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    joinedDate: '2020-09-01',
  },
  {
    id: 'usr-student-3',
    name: 'Anisa Rahmawati',
    nim_nip: '2203011012',
    email: 'anisa.rahma@mhs.ichsansatya.ac.id',
    role: 'student',
    department: 'D3 Kebidanan',
    studyProgram: 'Kebidanan Terapan',
    semester: 4,
    phone: '0878-1122-3344',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    joinedDate: '2022-09-01',
  },
  {
    id: 'usr-staff-1',
    name: 'Ns. Hendra Wijaya, S.Kep., M.Kep.',
    nim_nip: '198704122014021003',
    email: 'hendra.wijaya@ichsansatya.ac.id',
    role: 'nurse_staff',
    department: 'Laboratorium Terpadu Keperawatan',
    phone: '0813-8822-0199',
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    joinedDate: '2015-03-01',
  },
  {
    id: 'usr-admin-1',
    name: 'Ibu Ratna Dewi, S.ST., M.Kes.',
    nim_nip: '197906152008012001',
    email: 'ratna.dewi@ichsansatya.ac.id',
    role: 'admin',
    department: 'Koordinator Pengelola Laboratorium Kesehatan UIS',
    phone: '0811-9900-1122',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    joinedDate: '2010-01-15',
  },
];

export const LAB_ROOMS: LabRoom[] = [
  {
    id: 'room-1',
    code: 'LAB-KMB-01',
    name: 'Laboratorium Keperawatan Medikal Bedah (KMB)',
    building: 'Gedung B Fakultas Keperawatan',
    floor: 'Lantai 2',
    capacity: 25,
    supervisor: 'Ns. Hendra Wijaya, S.Kep., M.Kep.',
    status: 'AVAILABLE',
  },
  {
    id: 'room-2',
    code: 'LAB-ICU-02',
    name: 'Laboratorium Gawat Darurat & Kritis (ICU/Gadar)',
    building: 'Gedung B Fakultas Keperawatan',
    floor: 'Lantai 1',
    capacity: 20,
    supervisor: 'Ns. Faisal Akbar, S.Kep.',
    status: 'IN_USE',
    activeClass: 'Simulasi Resusitasi Jantung Paru (Profesi Ners)',
  },
  {
    id: 'room-3',
    code: 'LAB-MAT-03',
    name: 'Laboratorium Maternitas, Kebidanan & Anak',
    building: 'Gedung B Fakultas Keperawatan',
    floor: 'Lantai 3',
    capacity: 30,
    supervisor: 'Bdn. Siti Nurjanah, S.Tr.Keb.',
    status: 'AVAILABLE',
  },
  {
    id: 'room-4',
    code: 'LAB-KD-04',
    name: 'Laboratorium Keterampilan Dasar Keperawatan (KDK)',
    building: 'Gedung C Kampus Utama',
    floor: 'Lantai 2',
    capacity: 35,
    supervisor: 'Ns. Dian Anggraini, S.Kep.',
    status: 'AVAILABLE',
  },
  {
    id: 'room-5',
    code: 'LAB-OSCE-05',
    name: 'Ruang Ujian OSCE & Station Simulasi Klinis',
    building: 'Gedung C Kampus Utama',
    floor: 'Lantai 3',
    capacity: 40,
    supervisor: 'Ibu Ratna Dewi, M.Kes.',
    status: 'MAINTENANCE',
    activeClass: 'Kalibrasi Sensor Simulator & Audio Visual OSCE',
  },
];

export const INITIAL_EQUIPMENT: Equipment[] = [
  {
    id: 'eq-1',
    code: 'EQ-KMB-001',
    name: 'Manikin Resusitasi CPR Dewasa QCPR (Adult Resusci Anne)',
    category: 'Emergency & Critical Care',
    brand: 'Laerdal Medical',
    model: 'Resusci Anne QCPR Wireless',
    description:
      'Manikin latihan resusitasi kardiopulmoner tingkat lanjut dengan sensor feedback kompresi dada, ventilasi real-time, dan koneksi aplikasi bluetooth untuk simulasi BLS/ACLS.',
    totalQuantity: 8,
    availableQuantity: 5,
    borrowedQuantity: 2,
    maintenanceQuantity: 1,
    condition: 'EXCELLENT',
    location: 'Lab Gawat Darurat & Kritis (ICU/Gadar) - Gd. B Lt. 1, Lemari A-01',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=600&auto=format&fit=crop&q=80',
    specifications: [
      'Wireless Bluetooth Connectivity',
      'Real-time QCPR Feedback Sensor',
      'Anatomically accurate chest rise & fall',
      'Airway head tilt / chin lift capability',
      'Carotid pulse simulation bulb included',
    ],
    usageGuidelines: [
      'Gunakan face shield sekali pakai untuk setiap praktikan.',
      'Bersihkan jalur pernapasan dengan alkohol 70% setelah simulasi.',
      'Jangan menekan dengan benda tajam pada permukaan silikon dada.',
    ],
    isConsumable: false,
    requiresSpecialApproval: true,
    qrCode: 'UIS-EQ-KMB-001',
    createdAt: '2023-01-10',
    lastInspectionDate: '2026-08-15',
  },
  {
    id: 'eq-2',
    code: 'EQ-MAT-002',
    name: 'Manikin Simulasi Persalinan & Bayi Maternal Simulator',
    category: 'Maternity & Child Health',
    brand: 'Gaumard Scientific',
    model: 'NOELLE Maternal & Neonatal Simulator',
    description:
      'Simulator persalinan anatomis lengkap dengan mekanisme penurunan janin otomatis, plasenta, tali pusat, dan simulator bayi baru lahir untuk praktik APN dan resusitasi neonatus.',
    totalQuantity: 4,
    availableQuantity: 2,
    borrowedQuantity: 2,
    maintenanceQuantity: 0,
    condition: 'EXCELLENT',
    location: 'Lab Maternitas & Anak - Gd. B Lt. 3, Lemari M-02',
    imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=600&auto=format&fit=crop&q=80',
    specifications: [
      'Articulating birthing baby with placenta',
      'Automatic birth delivery carriage system',
      'Palpation abdomen cover for Leopold maneuvers',
      'Episiotomy perineal repair inserts included',
    ],
    usageGuidelines: [
      'Gunakan pelumas berbasis air (KY Jelly) pada jalan lahir.',
      'Dilarang menggunakan pelumas berbasis minyak/vaselin yang merusak lateks.',
      'Pastikan tali pusat terpasang kencang sebelum simulasi dorongan.',
    ],
    isConsumable: false,
    requiresSpecialApproval: true,
    qrCode: 'UIS-EQ-MAT-002',
    createdAt: '2023-03-12',
    lastInspectionDate: '2026-08-10',
  },
  {
    id: 'eq-3',
    code: 'EQ-DG-003',
    name: 'Stetoskop Kardiologi Klinis Master Classic III',
    category: 'Diagnostic & Vital Signs',
    brand: '3M Littmann',
    model: 'Classic III Special Edition Caribbean Blue',
    description:
      'Stetoskop diagnostik sensitivitas akustik tinggi dengan diafragma dual-frequency untuk auskultasi suara jantung, paru-paru, dan bising usus dewasa maupun pediatrik.',
    totalQuantity: 20,
    availableQuantity: 14,
    borrowedQuantity: 5,
    maintenanceQuantity: 1,
    condition: 'GOOD',
    location: 'Lab Keterampilan Dasar (KDK) - Gd. C Lt. 2, Rak Diagnostic 01',
    imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600&auto=format&fit=crop&q=80',
    specifications: [
      'Dual-lumen tubing acoustic design',
      'Tunable diaphragm technology (Adult & Pediatric side)',
      'Stainless steel precision chestpiece',
      'Soft-sealing ear tips with tight acoustic seal',
    ],
    usageGuidelines: [
      'Desinfeksi eartip dan diafragma dengan alcohol swab sebelum dan sesudah digunakan.',
      'Simpan dalam case pelindung, jangan ditekuk tajam di dalam saku.',
    ],
    isConsumable: false,
    requiresSpecialApproval: false,
    qrCode: 'UIS-EQ-DG-003',
    createdAt: '2023-02-20',
    lastInspectionDate: '2026-08-20',
  },
  {
    id: 'eq-4',
    code: 'EQ-DG-004',
    name: 'Tensimeter Aneroid Presisi + Manset Multi-Size',
    category: 'Diagnostic & Vital Signs',
    brand: 'Riester',
    model: 'Exacta Aneroid Sphygmomanometer',
    description:
      'Alat ukur tekanan darah manual presisi tinggi dengan manometer tahan goncangan, bola inflasi ergonomis, dan kelengkapan manset dewasa standar & obesitas.',
    totalQuantity: 18,
    availableQuantity: 12,
    borrowedQuantity: 6,
    maintenanceQuantity: 0,
    condition: 'EXCELLENT',
    location: 'Lab Keterampilan Dasar (KDK) - Gd. C Lt. 2, Rak Diagnostic 02',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80',
    specifications: [
      'Scale 0-300 mmHg accuracy +/- 2 mmHg',
      'Micro-filter protects release valve and measuring system',
      'Latex-free bulb with chrome-plated spoon',
      'Washable nylon cuff with velcro closure',
    ],
    usageGuidelines: [
      'Pastikan jarum penunjuk berada tepat di angka nol sebelum pengukuran.',
      'Lepaskan udara secara perlahan 2-3 mmHg per detik.',
    ],
    isConsumable: false,
    requiresSpecialApproval: false,
    qrCode: 'UIS-EQ-DG-004',
    createdAt: '2023-02-22',
    lastInspectionDate: '2026-08-18',
  },
  {
    id: 'eq-5',
    code: 'EQ-EM-005',
    name: 'Defibrillator AED Trainer Otomatis + Pad Sensor',
    category: 'Emergency & Critical Care',
    brand: 'ZOLL Medical',
    model: 'AED Plus Trainer with CPR-D-padz',
    description:
      'Alat peraga simulasi defibrilator eksternal otomatis dengan panduan suara bahasa Indonesia/Inggris, metronom ritme kompresi, dan kendali jarak jauh (remote) skenario ritme jantung.',
    totalQuantity: 6,
    availableQuantity: 3,
    borrowedQuantity: 3,
    maintenanceQuantity: 0,
    condition: 'EXCELLENT',
    location: 'Lab Gawat Darurat (ICU/Gadar) - Gd. B Lt. 1, Rak E-02',
    imageUrl: 'https://images.unsplash.com/photo-1583912267670-6575ad36240f?w=600&auto=format&fit=crop&q=80',
    specifications: [
      'Voice prompts for shockable / non-shockable scenarios',
      'Wireless infrared instructor remote control',
      'Reusable CPR-D training electrode pads',
      'Operates on 4 standard D-cell batteries',
    ],
    usageGuidelines: [
      'Hanya untuk keperluan latihan simulator, JANGAN ditempelkan pada manusia asli.',
      'Simpan pad latihan di atas plastik pelindung agar daya rekat awet.',
    ],
    isConsumable: false,
    requiresSpecialApproval: false,
    qrCode: 'UIS-EQ-EM-005',
    createdAt: '2023-05-18',
    lastInspectionDate: '2026-08-12',
  },
  {
    id: 'eq-6',
    code: 'EQ-NS-006',
    name: 'Infusion Pump Digital Micro/Macro Terumo',
    category: 'Nursing Skills',
    brand: 'Terumo Corporation',
    model: 'TE-171 Precision Infusion Pump',
    description:
      'Pompa infus elektronik cerdas untuk pengaturan laju tetesan cairan intravena (IV) dengan akurasi tinggi, sensor deteksi udara dalam selang, dan alarm oklusi tekanan.',
    totalQuantity: 10,
    availableQuantity: 6,
    borrowedQuantity: 3,
    maintenanceQuantity: 1,
    condition: 'GOOD',
    location: 'Lab Keperawatan Medikal Bedah - Gd. B Lt. 2, Lemari Elektromedis 01',
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&auto=format&fit=crop&q=80',
    specifications: [
      'Flow rate: 0.1 to 1200 mL/h',
      'Air-in-line ultrasonic bubble detection sensor',
      'Multi-step occlusion alarm setting',
      'Rechargeable internal Ni-MH battery backup (4 hours)',
    ],
    usageGuidelines: [
      'Selalu lakukan kalibrasi drop sensor sebelum memulai praktikum.',
      'Gunakan IV set khusus infusion pump untuk hasil tetesan akurat.',
      'Hubungkan ke sumber daya listrik saat disimpan untuk menjaga kesehatan baterai.',
    ],
    isConsumable: false,
    requiresSpecialApproval: false,
    qrCode: 'UIS-EQ-NS-006',
    createdAt: '2023-04-05',
    lastInspectionDate: '2026-08-01',
  },
  {
    id: 'eq-7',
    code: 'EQ-NS-007',
    name: 'Syringe Pump Presisi B. Braun Perfusor Space',
    category: 'Emergency & Critical Care',
    brand: 'B. Braun Melsungen AG',
    model: 'Perfusor Space Compact',
    description:
      'Pompa injeksi spuit terprogram untuk pemberian obat high-alert dan titrasi cairan konsentrasi tinggi dengan sensor pengenal ukuran syringe otomatis (5ml hingga 50ml).',
    totalQuantity: 8,
    availableQuantity: 5,
    borrowedQuantity: 3,
    maintenanceQuantity: 0,
    condition: 'EXCELLENT',
    location: 'Lab Gawat Darurat (ICU/Gadar) - Gd. B Lt. 1, Lemari Elektromedis 02',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    specifications: [
      'Syringe size compatibility: 2/3 ml, 5 ml, 10/12 ml, 20 ml, 50/60 ml',
      'Infusion rate accuracy: +/- 2%',
      'Bolus delivery rate: up to 1800 ml/h',
      'Integrated dose calculation and drug library',
    ],
    usageGuidelines: [
      'Pastikan syringe terkunci dengan benar pada slot penahan spuit.',
      'Bersihkan sisa cairan elektrolit pada permukaan plunger setelah dipakai.',
    ],
    isConsumable: false,
    requiresSpecialApproval: false,
    qrCode: 'UIS-EQ-NS-007',
    createdAt: '2023-06-11',
    lastInspectionDate: '2026-07-29',
  },
  {
    id: 'eq-8',
    code: 'EQ-NS-008',
    name: 'Manikin Lengan Latihan Flebotomi & Kanulasi IV (IV Arm Trainer)',
    category: 'Nursing Skills',
    brand: 'Nasco Healthcare / Simulaids',
    model: 'Advanced Venipuncture & Injection Arm',
    description:
      'Lengan simulator realistis dengan sistem vena ganda (cephalic, basilic, antecubital, & dorsal metacarpal) lengkap dengan sensasi "pop" saat jarum menembus lumen vena.',
    totalQuantity: 12,
    availableQuantity: 8,
    borrowedQuantity: 3,
    maintenanceQuantity: 1,
    condition: 'GOOD',
    location: 'Lab Keterampilan Dasar (KDK) - Gd. C Lt. 2, Rak Skill Pad 03',
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&auto=format&fit=crop&q=80',
    specifications: [
      'Synthetic veins and soft realistic skin cover',
      'Simulated blood flashback chamber',
      'Supports IV catheter insertion (Abocath 18G-24G)',
      'Intramuscular injection site in deltoid area',
    ],
    usageGuidelines: [
      'Gunakan cairan darah artifisial berbasis pewarna makanan larut air.',
      'Bilas saluran vena dengan air hangat setelah praktikum selesai agar tidak mengendap.',
      'Gunakan jarum tajam berukuran maksimal 20G untuk memperpanjang usia kulit silikon.',
    ],
    isConsumable: false,
    requiresSpecialApproval: false,
    qrCode: 'UIS-EQ-NS-008',
    createdAt: '2023-01-25',
    lastInspectionDate: '2026-08-14',
  },
  {
    id: 'eq-9',
    code: 'EQ-DG-009',
    name: 'Mesin Elektrokardiogram EKG 12-Lead Portabel',
    category: 'Diagnostic & Vital Signs',
    brand: 'GE Healthcare',
    model: 'MAC 600 Resting ECG Analysis System',
    description:
      'Perekam gelombang listrik jantung 12-lead dengan layar warna LCD, algoritma interpretasi Marquette 12SL, dan printer termal terintegrasi untuk praktikum interpretasi aritmia.',
    totalQuantity: 5,
    availableQuantity: 3,
    borrowedQuantity: 1,
    maintenanceQuantity: 1,
    condition: 'GOOD',
    location: 'Lab Keperawatan Medikal Bedah - Gd. B Lt. 2, Troli EKG 01',
    imageUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=600&auto=format&fit=crop&q=80',
    specifications: [
      '12-lead simultaneous ECG acquisition',
      '4.3 inch TFT color display',
      '80 mm roll thermal printout',
      'Electrode lead cable with clamp and bulb chest suction cups',
    ],
    usageGuidelines: [
      'Gunakan ECG conductive gel secukupnya pada elektroda dada.',
      'Bersihkan sisa gel pada suction bulb dengan lap basah segera setelah pakai.',
      'Hindari menarik kabel lead secara paksa saat mencabut.',
    ],
    isConsumable: false,
    requiresSpecialApproval: true,
    qrCode: 'UIS-EQ-DG-009',
    createdAt: '2023-04-19',
    lastInspectionDate: '2026-08-05',
  },
  {
    id: 'eq-10',
    code: 'EQ-NS-010',
    name: 'Set Simulator Kateterisasi Urin Pria & Wanita 2-in-1',
    category: 'Nursing Skills',
    brand: 'Kyoto Kagaku',
    model: 'Dual Gender Catheterization Trainer',
    description:
      'Model panggul anatomis presisi dengan organ reproduksi pria & wanita yang dapat ditukar, katup uretra resisten realistis, dan saluran pengeluaran urine saat balon kateter mengembang di vesika urinaria.',
    totalQuantity: 6,
    availableQuantity: 4,
    borrowedQuantity: 2,
    maintenanceQuantity: 0,
    condition: 'EXCELLENT',
    location: 'Lab Keterampilan Dasar (KDK) - Gd. C Lt. 2, Rak Skill Pad 04',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&auto=format&fit=crop&q=80',
    specifications: [
      'Interchangeable male and female genitalia modules',
      'Fluid reservoir for true urinary outflow confirmation',
      'Prostate enlargement simulation insert included',
      'Supports Foley catheters sizes 14 Fr - 18 Fr',
    ],
    usageGuidelines: [
      'Selalu gunakan jelly pelumas pada kateter sebelum dimasukkan ke meatus uretra.',
      'Kembangkan balon kateter hanya dengan aquadest, jangan pakai larutan garam yang mengkristal.',
    ],
    isConsumable: false,
    requiresSpecialApproval: false,
    qrCode: 'UIS-EQ-NS-010',
    createdAt: '2023-03-01',
    lastInspectionDate: '2026-08-11',
  },
  {
    id: 'eq-11',
    code: 'EQ-SR-011',
    name: 'Set Instrumen Jahit Luka & Bedah Minor (Minor Surgery Set)',
    category: 'Surgical & Sterile Instruments',
    brand: 'Aesculap / B. Braun',
    model: 'Standard Minor Surgical Instrument Tray (18 Pcs)',
    description:
      'Set instrumen bedah minor berbahan baja tahan karat (Stainless Steel 316 Medical Grade) lengkap dalam bak instrumen steril: pinset anatomis/cirurgis, gunting metzenbaum/angkat jahitan, klem hemostatik pean/kocher, needle holder Mayo-Hegar.',
    totalQuantity: 15,
    availableQuantity: 10,
    borrowedQuantity: 5,
    maintenanceQuantity: 0,
    condition: 'EXCELLENT',
    location: 'Lab KMB & Bedah - Gd. B Lt. 2, Lemari Instrumen Steril 01',
    imageUrl: 'https://images.unsplash.com/photo-1583912267953-b09e0787e6ca?w=600&auto=format&fit=crop&q=80',
    specifications: [
      'Bak instrumen 509 tutup',
      'Needle Holder Mayo-Hegar 14 cm (2 pcs)',
      'Pinset Anatomis & Sirurgis 14 cm (4 pcs)',
      'Gunting Operasi Lurus & Bengkok Tajam/Tumpul (2 pcs)',
      'Klem Arteri Pean Lurus & Bengkok (4 pcs)',
      'Klem Kocher Gigi (2 pcs)',
      'Handle Scalpel No. 3 & No. 4',
    ],
    usageGuidelines: [
      'Wajib dicuci bersih dan dikeringkan sebelum dimasukkan ke ruang autoklaf sterilisasi.',
      'Cek kelengkapan jumlah item instrumen saat serah terima di depan petugas lab.',
    ],
    isConsumable: false,
    requiresSpecialApproval: false,
    qrCode: 'UIS-EQ-SR-011',
    createdAt: '2023-01-15',
    lastInspectionDate: '2026-08-22',
  },
  {
    id: 'eq-12',
    code: 'EQ-EM-012',
    name: 'Suction Pump Portable Aspirator Lendir & Sekresi',
    category: 'Emergency & Critical Care',
    brand: 'Yuwell Healthcare',
    model: '7E-A Electric Suction Apparatus',
    description:
      'Mesin penyedot dahak dan lendir saluran napas bertekanan negatif tinggi dengan tabung penampung polikarbonat 1000ml dan filter antibakteri pelindung overflow.',
    totalQuantity: 8,
    availableQuantity: 5,
    borrowedQuantity: 2,
    maintenanceQuantity: 1,
    condition: 'GOOD',
    location: 'Lab Gawat Darurat (ICU/Gadar) - Gd. B Lt. 1, Rak E-03',
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    specifications: [
      'Max negative pressure: >= 0.075 MPa',
      'Pumping rate: >= 15 L/min',
      'Reservoir volume: 1000 mL with overflow cutoff',
      'Noise level: <= 65 dB(A)',
    ],
    usageGuidelines: [
      'Gunakan kateter suction sekali pakai sesuai ukuran (Fr 8 - Fr 14).',
      'Segera kosongkan tabung dan disinfeksi wadah setelah selesai digunakan.',
    ],
    isConsumable: false,
    requiresSpecialApproval: false,
    qrCode: 'UIS-EQ-EM-012',
    createdAt: '2023-05-02',
    lastInspectionDate: '2026-07-25',
  },
  {
    id: 'eq-13',
    code: 'EQ-DG-013',
    name: 'Pulse Oximeter Digital Fingertip & Pediatric Probe',
    category: 'Diagnostic & Vital Signs',
    brand: 'ChoiceMMed',
    model: 'OxyWatch OLED Dual Color SpO2 Monitor',
    description:
      'Alat saturasi oksigen darah kapiler non-invasif dengan grafik pletismogram real-time, indikator indeks perfusi (PI), dan alarm visual batas hipoksia.',
    totalQuantity: 25,
    availableQuantity: 20,
    borrowedQuantity: 5,
    maintenanceQuantity: 0,
    condition: 'EXCELLENT',
    location: 'Lab Keterampilan Dasar (KDK) - Gd. C Lt. 2, Laci Vital Sign 01',
    imageUrl: 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=600&auto=format&fit=crop&q=80',
    specifications: [
      'SpO2 measuring range: 70% - 100% (accuracy +/- 2%)',
      'Pulse rate range: 30 - 250 bpm',
      'Dual color OLED display with 6 display modes',
      'Low power battery indicator',
    ],
    usageGuidelines: [
      'Pastikan jari tidak memakai kutek atau cat kuku gelap.',
      'Bersihkan sensor infrared dengan tisu beralkohol setelah dipakai.',
    ],
    isConsumable: false,
    requiresSpecialApproval: false,
    qrCode: 'UIS-EQ-DG-013',
    createdAt: '2023-01-18',
    lastInspectionDate: '2026-08-19',
  },
  {
    id: 'eq-14',
    code: 'EQ-NS-014',
    name: 'Nebulizer Kompresor Terapi Inhalasi Omron',
    category: 'Nursing Skills',
    brand: 'Omron Healthcare',
    model: 'NE-C28 CompAIR Heavy Duty',
    description:
      'Alat aerosol terapi penguapan bronkodilator untuk pasien asma dan PPOK dengan teknologi Virtual Valve (V.V.T) yang meminimalisir pemborosan obat.',
    totalQuantity: 9,
    availableQuantity: 6,
    borrowedQuantity: 3,
    maintenanceQuantity: 0,
    condition: 'GOOD',
    location: 'Lab KMB - Gd. B Lt. 2, Rak Terapi Oksigen 02',
    imageUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600&auto=format&fit=crop&q=80',
    specifications: [
      'Particle size (MMAD): approx 3.0 um',
      'Nebulization rate: 0.4 mL/min',
      'Medication cup capacity: 2 mL to 7 mL',
      'Includes adult mask, child mask, mouthpiece',
    ],
    usageGuidelines: [
      'Jangan menuang cairan obat melebihi garis batas 7ml pada medicine cup.',
      'Keringkan seluruh selang dan masker setelah dicuci dengan air bersih.',
    ],
    isConsumable: false,
    requiresSpecialApproval: false,
    qrCode: 'UIS-EQ-NS-014',
    createdAt: '2023-03-30',
    lastInspectionDate: '2026-08-08',
  },
  {
    id: 'eq-15',
    code: 'EQ-MAT-015',
    name: 'Doppler Fetal Heart Rate (FHR) Detektor Jantung Janin',
    category: 'Maternity & Child Health',
    brand: 'Bistos',
    model: 'Hi-bebe BT-200 Sound Doppler',
    description:
      'Alat ultrasonografi doppler saku dengan probe 2 MHz untuk mendengarkan dan menghitung denyut jantung janin sejak usia kehamilan 10-12 minggu dengan pengeras suara terintegrasi.',
    totalQuantity: 8,
    availableQuantity: 5,
    borrowedQuantity: 3,
    maintenanceQuantity: 0,
    condition: 'EXCELLENT',
    location: 'Lab Maternitas & Anak - Gd. B Lt. 3, Lemari M-03',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=600&auto=format&fit=crop&q=80',
    specifications: [
      'High sensitivity 2.0 MHz ultrasound probe',
      'Large LCD display for FHR calculation (50-240 bpm)',
      'Built-in loudspeaker with volume wheel control',
      'Acoustic gel indicator',
    ],
    usageGuidelines: [
      'Wajib menggunakan USG gel konduktif pada permukaan probe doppler.',
      'Segera bersihkan probe dengan kain halus setelah selesai pemeriksaan.',
    ],
    isConsumable: false,
    requiresSpecialApproval: false,
    qrCode: 'UIS-EQ-MAT-015',
    createdAt: '2023-02-14',
    lastInspectionDate: '2026-08-16',
  },
];

export const INITIAL_BORROWING_REQUESTS: BorrowingRequest[] = [
  {
    id: 'req-001',
    ticketNumber: 'REQ-202608-0042',
    userId: 'usr-student-1',
    userName: 'Siti Nurhaliza Putri',
    userNim: '2102041019',
    userDepartment: 'S1 Keperawatan',
    userPhone: '0812-9842-1102',
    userRole: 'student',
    purpose: 'Ujian OSCE / Skill Lab Keperawatan Kritis (ACLS)',
    courseName: 'Keperawatan Gawat Darurat & Kritis II',
    supervisorLecturer: 'Ns. Faisal Akbar, S.Kep., M.Kep.',
    borrowDate: '2026-08-25',
    expectedReturnDate: '2026-08-27',
    status: 'BORROWED',
    items: [
      {
        equipmentId: 'eq-1',
        equipmentCode: 'EQ-KMB-001',
        equipmentName: 'Manikin Resusitasi CPR Dewasa QCPR',
        quantity: 1,
        imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=600&auto=format&fit=crop&q=80',
        location: 'Lab ICU/Gadar - Gd. B Lt. 1',
        conditionAtBorrow: 'EXCELLENT',
      },
      {
        equipmentId: 'eq-5',
        equipmentCode: 'EQ-EM-005',
        equipmentName: 'Defibrillator AED Trainer Otomatis',
        quantity: 1,
        imageUrl: 'https://images.unsplash.com/photo-1583912267670-6575ad36240f?w=600&auto=format&fit=crop&q=80',
        location: 'Lab ICU/Gadar - Gd. B Lt. 1',
        conditionAtBorrow: 'EXCELLENT',
      },
    ],
    handoverStaffName: 'Ns. Hendra Wijaya, S.Kep.',
    createdAt: '2026-08-24T09:15:00Z',
    updatedAt: '2026-08-25T08:00:00Z',
  },
  {
    id: 'req-002',
    ticketNumber: 'REQ-202608-0043',
    userId: 'usr-student-1',
    userName: 'Siti Nurhaliza Putri',
    userNim: '2102041019',
    userDepartment: 'S1 Keperawatan',
    userPhone: '0812-9842-1102',
    userRole: 'student',
    purpose: 'Praktikum Mandiri Mandat Dosen: Injeksi & Infus Pump',
    courseName: 'Keterampilan Dasar Keperawatan Medikal',
    supervisorLecturer: 'Ns. Dian Anggraini, S.Kep.',
    borrowDate: '2026-08-26',
    expectedReturnDate: '2026-08-26',
    status: 'READY_TO_PICKUP',
    items: [
      {
        equipmentId: 'eq-6',
        equipmentCode: 'EQ-NS-006',
        equipmentName: 'Infusion Pump Digital Micro/Macro Terumo',
        quantity: 1,
        imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&auto=format&fit=crop&q=80',
        location: 'Lab KMB - Gd. B Lt. 2',
      },
      {
        equipmentId: 'eq-8',
        equipmentCode: 'EQ-NS-008',
        equipmentName: 'Manikin Lengan Flebotomi & IV Arm Trainer',
        quantity: 1,
        imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&auto=format&fit=crop&q=80',
        location: 'Lab KDK - Gd. C Lt. 2',
      },
    ],
    adminNotes: 'Alat telah disiapkan di Meja Layanan Lab KMB Lt. 2. Harap tunjukkan KTM & QR tiket saat pengambilan.',
    createdAt: '2026-08-25T14:30:00Z',
    updatedAt: '2026-08-26T07:45:00Z',
  },
  {
    id: 'req-003',
    ticketNumber: 'REQ-202608-0044',
    userId: 'usr-student-2',
    userName: 'Dimas Arya Pratama',
    userNim: '2102041044',
    userDepartment: 'Profesi Ners',
    userPhone: '0857-3312-9901',
    userRole: 'student',
    purpose: 'Simulasi Penanganan Syok & EKG Lead di Stase ICU',
    courseName: 'Stase Keperawatan Gawat Darurat (Profesi Ners)',
    supervisorLecturer: 'Ns. Hendra Wijaya, M.Kep.',
    borrowDate: '2026-08-26',
    expectedReturnDate: '2026-08-28',
    status: 'PENDING',
    items: [
      {
        equipmentId: 'eq-9',
        equipmentCode: 'EQ-DG-009',
        equipmentName: 'Mesin Elektrokardiogram EKG 12-Lead Portabel',
        quantity: 1,
        imageUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=600&auto=format&fit=crop&q=80',
        location: 'Lab KMB - Gd. B Lt. 2',
      },
      {
        equipmentId: 'eq-7',
        equipmentCode: 'EQ-NS-007',
        equipmentName: 'Syringe Pump Presisi B. Braun Perfusor',
        quantity: 1,
        imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
        location: 'Lab ICU/Gadar - Gd. B Lt. 1',
      },
    ],
    createdAt: '2026-08-26T06:20:00Z',
    updatedAt: '2026-08-26T06:20:00Z',
  },
  {
    id: 'req-004',
    ticketNumber: 'REQ-202608-0038',
    userId: 'usr-student-3',
    userName: 'Anisa Rahmawati',
    userNim: '2203011012',
    userDepartment: 'D3 Kebidanan',
    userPhone: '0878-1122-3344',
    userRole: 'student',
    purpose: 'Praktik Asuhan Persalinan Normal (APN) & DJJ',
    courseName: 'Asuhan Kebidanan Persalinan & BBL',
    supervisorLecturer: 'Bdn. Siti Nurjanah, S.Tr.Keb.',
    borrowDate: '2026-08-20',
    expectedReturnDate: '2026-08-22',
    actualReturnDate: '2026-08-22T16:00:00Z',
    status: 'RETURNED',
    items: [
      {
        equipmentId: 'eq-2',
        equipmentCode: 'EQ-MAT-002',
        equipmentName: 'Manikin Simulasi Persalinan & Bayi Maternal Simulator',
        quantity: 1,
        imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=600&auto=format&fit=crop&q=80',
        location: 'Lab Maternitas & Anak - Gd. B Lt. 3',
        conditionAtBorrow: 'EXCELLENT',
        conditionAtReturn: 'EXCELLENT',
        returnNotes: 'Alat bersih, cairan lubricant telah dibilas sempurna.',
      },
      {
        equipmentId: 'eq-15',
        equipmentCode: 'EQ-MAT-015',
        equipmentName: 'Doppler Fetal Heart Rate (FHR)',
        quantity: 1,
        imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=600&auto=format&fit=crop&q=80',
        location: 'Lab Maternitas & Anak - Gd. B Lt. 3',
        conditionAtBorrow: 'EXCELLENT',
        conditionAtReturn: 'EXCELLENT',
      },
    ],
    handoverStaffName: 'Ns. Hendra Wijaya',
    returnStaffName: 'Ibu Ratna Dewi',
    createdAt: '2026-08-19T10:00:00Z',
    updatedAt: '2026-08-22T16:00:00Z',
  },
  {
    id: 'req-005',
    ticketNumber: 'REQ-202608-0029',
    userId: 'usr-student-2',
    userName: 'Dimas Arya Pratama',
    userNim: '2102041044',
    userDepartment: 'Profesi Ners',
    userPhone: '0857-3312-9901',
    userRole: 'student',
    purpose: 'Latihan Hecting & Jahit Luka Perineum',
    courseName: 'Bedah Minor & Perawatan Luka Akut',
    supervisorLecturer: 'Ns. Dian Anggraini, S.Kep.',
    borrowDate: '2026-08-21',
    expectedReturnDate: '2026-08-24',
    status: 'OVERDUE',
    items: [
      {
        equipmentId: 'eq-11',
        equipmentCode: 'EQ-SR-011',
        equipmentName: 'Set Instrumen Jahit Luka & Bedah Minor',
        quantity: 1,
        imageUrl: 'https://images.unsplash.com/photo-1583912267953-b09e0787e6ca?w=600&auto=format&fit=crop&q=80',
        location: 'Lab KMB - Gd. B Lt. 2',
        conditionAtBorrow: 'EXCELLENT',
      },
    ],
    adminNotes: 'Telah dikirimkan peringatan via WhatsApp & email kampus. Denda keterlambatan Rp 10.000/hari.',
    fineAmount: 20000,
    createdAt: '2026-08-20T11:00:00Z',
    updatedAt: '2026-08-26T00:00:00Z',
  },
];

export const INITIAL_MAINTENANCE_RECORDS: MaintenanceRecord[] = [
  {
    id: 'maint-1',
    ticketNumber: 'MNT-202608-01',
    equipmentId: 'eq-1',
    equipmentName: 'Manikin Resusitasi CPR Dewasa QCPR (Unit #03)',
    equipmentCode: 'EQ-KMB-001',
    location: 'Lab Gawat Darurat (ICU/Gadar)',
    issueDescription: 'Sensor Bluetooth koneksi QCPR feedback terputus-putus saat kompresi cepat.',
    reportedBy: 'Ns. Faisal Akbar, S.Kep.',
    reportedDate: '2026-08-20',
    status: 'IN_PROGRESS',
    technician: 'PT. Medika Elektromedika Prima',
    cost: 450000,
    priority: 'HIGH',
    notes: 'Modul sensor nirkabel sedang diuji ulang firmware.',
  },
  {
    id: 'maint-2',
    ticketNumber: 'MNT-202608-02',
    equipmentId: 'eq-9',
    equipmentName: 'Mesin Elektrokardiogram EKG 12-Lead Portabel (Unit #02)',
    equipmentCode: 'EQ-DG-009',
    location: 'Lab Keperawatan Medikal Bedah',
    issueDescription: 'Kalibrasi rutin 6 bulanan dan penggantian kabel lead V1-V2 yang longgar.',
    reportedBy: 'Ibu Ratna Dewi, M.Kes.',
    reportedDate: '2026-08-15',
    status: 'SCHEDULED',
    technician: 'Teknisi Biomedis Kampus UIS',
    cost: 150000,
    priority: 'MEDIUM',
  },
  {
    id: 'maint-3',
    ticketNumber: 'MNT-202607-09',
    equipmentId: 'eq-6',
    equipmentName: 'Infusion Pump Digital Terumo (Unit #05)',
    equipmentCode: 'EQ-NS-006',
    location: 'Lab KMB',
    issueDescription: 'Alarm sensor drop terlalu sensitif saat menggunakan selang makro.',
    reportedBy: 'Ns. Hendra Wijaya',
    reportedDate: '2026-07-20',
    status: 'COMPLETED',
    technician: 'Teknisi Biomedis Kampus UIS',
    cost: 75000,
    completedDate: '2026-07-23',
    priority: 'LOW',
    notes: 'Sensor optik dibersihkan dari debu dan dikalibrasi ulang.',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'usr-student-1',
    title: 'Pengajuan Peminjaman Siap Diambil!',
    message: 'Tiket #REQ-202608-0043 telah disetujui petugas. Silakan ambil alat di Meja Layanan Lab KMB Gd. B Lt. 2.',
    type: 'request_status',
    isRead: false,
    createdAt: '2026-08-26T07:45:00Z',
    link: '/student/borrowings/req-002',
  },
  {
    id: 'notif-2',
    userId: 'usr-student-1',
    title: 'Pengingat Batas Pengembalian',
    message: 'Peminjaman #REQ-202608-0042 (Manikin CPR & AED) jatuh tempo besok, 27 Agustus 2026.',
    type: 'due_reminder',
    isRead: false,
    createdAt: '2026-08-26T06:00:00Z',
    link: '/student/borrowings/req-001',
  },
  {
    id: 'notif-3',
    targetRole: 'nurse_staff',
    title: 'Permintaan Peminjaman Baru',
    message: 'Mahasiswa Dimas Arya Pratama mengajukan permohonan pinjam Mesin EKG & Syringe Pump.',
    type: 'request_status',
    isRead: false,
    createdAt: '2026-08-26T06:20:00Z',
    link: '/staff/requests',
  },
  {
    id: 'notif-4',
    targetRole: 'nurse_staff',
    title: 'Peringatan Alat Overdue!',
    message: 'Peminjaman #REQ-202608-0029 (Set Jahit Bedah Minor) telah melewati batas waktu 2 hari.',
    type: 'overdue',
    isRead: false,
    createdAt: '2026-08-25T08:00:00Z',
    link: '/staff/returns',
  },
];
