# Generated by Django 5.2.16 on 2026-09-03 01:55

import borrowings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingRequest',
            fields=[
                ('id', models.CharField(default=borrowings.models.make_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('purpose', models.TextField()),
                ('course_name', models.CharField(blank=True, default='', max_length=255)),
                ('supervisor_lecturer', models.CharField(blank=True, default='', max_length=255)),
                ('borrow_date', models.DateField()),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('READY_TO_PICKUP', 'Ready to Pickup'), ('BORROWED', 'Borrowed'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=24)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('handover_staff_name', models.CharField(blank=True, default='', max_length=255)),
                ('return_staff_name', models.CharField(blank=True, default='', max_length=255)),
                ('signature_student', models.TextField(blank=True, default='')),
                ('signature_staff', models.TextField(blank=True, default='')),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowing_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowingItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('condition_at_borrow', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('MAINTENANCE_REQUIRED', 'Maintenance Required'), ('DAMAGED', 'Damaged')], max_length=30, null=True)),
                ('condition_at_return', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('MAINTENANCE_REQUIRED', 'Maintenance Required'), ('DAMAGED', 'Damaged')], max_length=30, null=True)),
                ('return_notes', models.TextField(blank=True, default='')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowing_items', to='equipment.equipment')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='borrowings.borrowingrequest')),
            ],
        ),
    ]
