# Generated by Django 5.2.17 on 2026-09-25 09:09

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabDocument',
            fields=[
                ('id', models.CharField(default=documents.models.make_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('document_type', models.CharField(choices=[('SOP', 'SOP (Standar Operasional Prosedur)'), ('GENERAL', 'General')], default='SOP', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
